version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devlog
    ports:
      - 5433:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge